### ISSUE TITLE
NO OUTPUT FILES CREATED

### ISSUE THREAD

**Issue by tim009** [esh-b/Feature-based-opinion-mining#1]
Hi ,

i ran the main.py file, the code executed properly but it did not create any featureScore.txt, positiveReviews.txt, negativeReviews.txt  files.

**Comment by esh-b** [comment]
@saivineeth1074 Can you check that out?

**Comment by esh-b** [comment]
@tim009 The issue is fixed. 
Let me know incase of any other issues.
