### ISSUE TITLE
3 output files not being created

### ISSUE THREAD

**Issue by anoushka1196** [esh-b/Feature-based-opinion-mining#2]
I tried working on this. 
The 3 main files are not being created :- 
 featureScore.txt - contains all the potential features about the product and their scores. 
 positiveReviews.txt - contains all the positive reviews as classified by the algorithm. 
 negativeReviews.txt - which contains all the negative reviews
 
 Is there any way this issue can be solved?

**Comment by esh-b** [comment]
The issue is fixed. Btw, the project is just the implementation of the paper. Improvements could be made especially in feature extraction.
Let me know incase of any other issues.

**Comment by anoushka1196** [comment]
Thankyou so much
